package appB;

// This code demonstrates how to use a Java record by creating a Customer record instance and accessing its components just like a regular class.

public class UsingRecords {
  public static void main(String[] args) {
    usingARecordLooksJustLikeANormalClass();
  }

  // Method showing how to instantiate and use a record similar to a normal class
  static void usingARecordLooksJustLikeANormalClass() {
    // Create a new Customer record with id 7 and name "Trisha"
    Customer customer = new Customer(7, "Trisha");

    // Print the record using the autogenerated toString()
    System.out.println(customer);

    // Access the 'name' component using the autogenerated accessor method
    System.out.println(customer.name());

    // Additional print statements showing the same information
    System.out.println("customer = " + customer);
    System.out.println("customer.name() = " + customer.name());
  }
}
